variable "root_account_ids" {}
variable "ami_prefix" {}
variable "instance_type" {}
variable "public_subnets" {}
variable "domain_name" {}
variable "igw_id" {}
variable "vpc_id" {}
variable "ssh_key_name" {}
variable "environment" {}
